format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/accessom2_restart.nml
  hashes:
    binhash: 3ab270fa2d054d0b7562d01d6c9e9f30
    md5: 4b89ce5222716eb61d7a47223bd07150
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/grid.nc
  hashes:
    binhash: ac2827cb4bc36a4527fd8e370ab95358
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/i2o.nc
  hashes:
    binhash: 1d39de7e2a229e2cec1643773598a610
    md5: d78d886c03d56844abb6af1d4676bbc6
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/ice.restart_file
  hashes:
    binhash: 83afae149ee07d4cec2c14b597538948
    md5: 08f787cacd3586f5a701c097a397a358
work/ice/RESTART/iced.1983-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/iced.1983-01-01-00000.nc
  hashes:
    binhash: 1102c58304022b780c50bdfdf58c7e09
    md5: e3f02750e5d8f1430b3b3a528654cb36
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/kmt.nc
  hashes:
    binhash: ba36422db755fed901754184060cb63b
    md5: 576e78b474c37f61a6fb45c9f5692bc6
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/monthly_sstsss.nc
  hashes:
    binhash: 83ed50dcc5e3dde7d718a385f7e93536
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/o2i.nc
  hashes:
    binhash: b86b053ec5baf38f6e0d2e28d76342f3
    md5: 76a52a8914b32aaa7dd31761e774bcc8
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/sicemass.nc
  hashes:
    binhash: ae1fbb41265256a1253387effe8ee430
    md5: a2d7aa8f28e67b5a0b24ea378c7497ed
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ice/u_star.nc
  hashes:
    binhash: d4cbbc042013d54c2ea651a9ffa7dd9a
    md5: a5afca7c03088841e6bd77064e18133c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_age.res.nc
  hashes:
    binhash: 8e05d31f27168c29a5de72fdfebe46ac
    md5: 8872821ec0e15dc6920655671841aa3e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b78ad5920c79ed53ea5a7fe137ac9886
    md5: 6bcf3090bb94e860f20cc40c6821fa43
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cb13bf96619c13dc68a36f45ae12d0d4
    md5: a6a087250e1a94753a14721a2ab98335
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_density.res.nc
  hashes:
    binhash: e22f862e332a3dff2c38c698df1903e8
    md5: 00255bddf7cc76ea2ccd549b85f0c93d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8777c1d64faab512705f997e3e41bc59
    md5: c048f91e94643a13c620b3ba3dc72797
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 34c7edcb5d31b1fbdb887f51a3a9d74a
    md5: 26c63a8bc0663a66bd42c29c5881eacd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ffc04bb6bd5b43e601cd715f64557049
    md5: 57384b67fd2b8ac8bd883fcd86bcca9f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f17633fef9236ee9f1fcbe0e77ea71c0
    md5: e99d84b01d5d44332e4c404fa24c2fb2
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_solo.res
  hashes:
    binhash: 4292bc87fdf7ec50241b3ba1defd0311
    md5: d0ec5b36a7a0a535980cf99347c1d0cb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6bb5de3ed4a428a99ba2c4688b3c86f3
    md5: bae73ecb505b8968569f3ecd9909e4e0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1481984dcff9a5d03fdaeff1e31c67c3
    md5: 27ee9511b4282e6d4f42aca2c8f68e9b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_tracer.res
  hashes:
    binhash: 613e5831770b4a4492729546ae83a6cc
    md5: 078a2ef87b50d1609522610c42a61b58
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cf9e31f67c71433662a8882b2e330148
    md5: 236ab3d080c82582ae146e81c93e1250
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_era5_iaf/restart002/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9ba6d98a44c0159fbf002889a2764bf0
    md5: c606e1ab76474e1f9496c50586904c6c
